reactjs/react-tabs

package.json
This fixes an unexpected token error when requiring react-tabs in browserify.
=> Add Reactify transform for Browserify

lib/helpers/styles.js
A duplicate object property throws in strict mode.
=> remove duplicate object property from styles hash

lib/components/Tab.js, lib/components/TabPanel.js
I was getting `Warning: Failed propType: Invalid prop `children` supplied to `TabPanel`.` in development. 
This eliminates prevents that error by adding `array` to the list of acceptable `propTypes` for `children`.
=> Add array to children propTypes

README.md, lib/components/TabPanel.js, lib/components/Tabs.js, lib/components/__tests__/Tabs-test.js
The default is to inline `display: none;` which should cover most use
cases. Changing it to always render the childern of TabPanel's also
allows for overriding of the styles so that animation between content
panes is easier.
=> always render TabPanel children.

lib/components/Tab.js, lib/components/TabList.js, lib/components/TabPanel.js, lib/components/Tabs.js
I was not sure if it was by intention, but inside the files there were a mix of tabs and spaces. I converted all of them to spaces.
\t => \s\s
=> Replace all tabs with spaces

README.md
As the react dependency is 0.13, it is not needed anymore.
Sorry for spamming with PR :)
=> Remove JSX comment from example

lib/helpers/styles.js
I'm using `react-tabs` alongside a CSS framework that sets the global text color to white. This PR fixes that by explicitly setting the color to black.
=> Avoid white-on-white Tab Labels

README.md
`onSelect`-handle was called `{this.handleSelected}` while the method was `handleSelect`. This PR fixes that minor issue.
=> Fix onSelect method name in README.md

lib/components/Tabs.js
Moving injection of styles from `componentWillMount` to `componentDidMount`. Solves https://github.com/rackt/react-tabs/issues/45
=> [fixed] Server Side Rendering won't work with default styles #45

lib/components/Tabs.js
Was changed in f360ce672b291d19fa1806e535d7bf2092b30892
and it is the only place where focusRenderTabPanel appears, so i think this was done by mistake.
=> Fix defaultProps for forceRenderTabPanel

package.json
for example it is not possible to install classnames 2.2.1. And as you are really slow in responding to even the smallest changes, i made the dependency ^2.2 so even 2.3 could be used.
=> Soften requirements so updates can be installed

src/components/Tabs.js, src/components/__tests__/Tabs-test.js
Add a check that checks if the tab belongs to the container.
Fixes #54
Fixes #91
=> Fix nesting of multiple instances of react-tabs

examples/focus/app.js, src/components/Tabs.js, src/components/__tests__/Tabs-test.js
Post my comment in #51, I investigated this issue some more and concluded that the problem was in making a decision based on reading from outdated local state. I'll repeat what I wrote in my commit message here:
> ### What?
This changes the `copyPropsToState` method to take a second argument (`state`), enabling using it when feeding `setState` a callback so we can do a transactional update in `componentWillReceiveProps`.
This is needed because previously we were hitting a race condition whenever the parent component was triggering a rerender when using `setState` in its `onSelect` handler: `componentWillReceiveProps` would be triggered, calling `copyPropsToState`, which in turn read from `this.state` synchronously before the state changes triggered in `Tabs`'s own `setSelected` method had …
=> Allow setState in onSelect (fixes #51)

package.json
See #111. Figured I'd make a PR with my suggested fix. After merging, the version would need to be bumped (including git tag) and published to npm for the build to be picked up by both bower and npmcdn.
=> Fix outdated umd build (fixes #111)

examples/basic/app.js, src/components/TabList.js, src/components/Tabs.js, src/components/__tests__/Tabs-test.js, src/helpers/childrenPropType.js
Allows to add additional elements inside a TabList.
I've disabled the check that was throwing a warning when an element different from Tab was added to the TabList. Seems working well.
I needed to do this since I need to add a fake tab at the end of the TabList, like this:
```html
<Tabs>
<TabList>
<Tab>Foo</Tab>
<div>+</div>
</TabList>
<TabPanel>Hello</TabPanel>
</Tabs>
```
Maybe we can do the same for TabPanels, if needed.
Let me know your thoughts :)
=> Allow other components inside TabList

src/components/Tab.js, src/components/TabList.js, src/components/TabPanel.js, src/components/Tabs.js, src/helpers/childrenPropType.js
Refactor component with es6 class syntax, https://github.com/reactjs/react-tabs/issues/125
=> Use es6 class

bower.json, src/components/Tabs.js, src/components/__tests__/Tabs-test.js, src/helpers/childrenPropType.js
Hi All 👋
I noticed a bad link in another project, linking to `github.com/rackt/redux` which is now held by somebody else it seems - who also have a `redux` repo, just to confuse things.
I opened a PR in that project but thought I'd have a quick look at other occurrences and noticed that there are a few vestiges here. They updated links seem to point to the correct issues and PRs in `react-tabs`s new home at `/reactjs/`.
:)
=> Replace url references to rackt/react-tabs with reactjs/react-tabs

examples/basic/app.js, examples/conditional/app.js, examples/dyno/app.js, examples/focus/app.js, examples/nested/app.js
Hello, I hope everything is well, I contributed a small change on the examples folder, changed ReactDOM.render to render, to to be consistent with the README on the front page that uses render also, hope this helps in a little way.
=> change ReactDOM.render to render

README.md
Hi, I think it would be helpful to have a badge pointing to the npm package as there isn't a link anywhere in the README.
=> Add NPM package badge

CHANGELOG.md, README.md, examples/basic/app.js, package.json, src/components/Tab.js, src/components/TabList.js, src/components/TabPanel.js, src/components/Tabs.js, src/components/UncontrolledTabs.js, src/components/__tests__/Tab-test.js, src/components/__tests__/TabList-test.js, src/components/__tests__/TabPanel-test.js, src/components/__tests__/Tabs-test.js, style/react-tabs.css, style/react-tabs.less, style/react-tabs.scss
=> Cleanup for 1.0

src/components/UncontrolledTabs.js, src/components/__tests__/Tabs-node-test.js
=> Fix activeElement check #193

src/components/UncontrolledTabs.js
Implementing `react-tabs` with custom `TabList` + `Tab` components can be currently done using the corresponding `tabsRole` static property, and this is neat. However, the check within `isTabNode()` relies on the tagName being an `LI` element, and this has some limitations for cases where a custom `<TabList />` component's markup does not match the `ul > li` structure.
=> feat(tabs): verify click tabNode using *[role=tab]

src/components/UncontrolledTabs.js
The last commit removed the use of `nodeName` within the check of `isTabNode(node)`, but the event can potentially bubble up all the way to the `DocumentElement` whose interface has no `getAttribute()` method.
=> fix(tabs): click wrapper container bubbles up and getAttribute() throws

package.json
`yarn rollup -c` is invalid, so `dist` directory cannot be created, fix it.
=> fix scripts build:umd

package.json
I'm working on optimizing the size of the bundle.
And I noticed that in esm build a lot of repetitive code in the components.
Which generates the babel:
```js
function _extends() {/* ... */ }
function _objectWithoutProperties(source, excluded) {/* ... */ }
function _inheritsLoose(subClass, superClass) {/* ... */ }
```
Babel-runtime takes these repetitive functions to separate modules.
which significantly reduces the size
=> Added src folder!

README.md
If you build with babel/webkit (which create-react-app does), this example gives the error:
'this' is not allowed before super()
Adding `super();` in the constructor allows it to build properly without error.
=> To avoid the babel "'this' is not allowed before super()" error

webpack.config.js
I tried run `npm run start` but there's an error as following
```
.../react-tabs\webpack.config.js:40
);
^
SyntaxError: Unexpected token )
```
after removing trailing comma for parameters of ` plugins.push` function, it works fine. 
I don't know if this error only occur in node version 6.10.0
=> Fix unable to serve example website in node v.6.10.0

src/components/UncontrolledTabs.js
According to [WAI-ARIA Authoring Practices](https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/#tabpanel), we can navigate the tab list with `Home` and `End` key. Even though it's optional, It'd be nice if react-tabs supports it.
=> Add support for home and end key on tab list

examples/src/components/ExampleItem.js, examples/src/components/examples/Avengers.js
- Use onChange instead of onClick for checkbox in examples
- Add missing key props in two lists in examples
=> Fix two warnings in the examples

README.md, src/components/Tabs.js, src/components/UncontrolledTabs.js, src/components/__tests__/Tabs-node-test.js
I've ran into a use case where the focus between tabs wasn't properly handled while navigating using the arrow keys due to  having `react-tabs` rendered on an `iframe`.
Inspired by [`downshift`](https://github.com/downshift-js/downshift#environment), this PR adds an `environment` prop to allow users to specify a different `window` if they need to.
=> Add environment prop

README.md
No idea when/how this broke, or if it works on a website somewhere but this at least fixes it in GitHub 👍🏻
=> Update README to use local path to browser stack logo

.babelrc.js, package.json
BREAKING CHANGE: The package now does use `Object.assign` directly instead of babel helpers. In older browsers you might need to pollyfill these. `react` itself has the same dependency.
=> Improve output code size and do not package tests

package.json, src/components/Tab.js, src/components/TabPanel.js, src/components/UncontrolledTabs.js, src/components/__tests__/Tab-test.js, src/components/__tests__/TabList-test.js, src/components/__tests__/TabPanel-test.js, src/components/__tests__/Tabs-errors-test.js, src/components/__tests__/Tabs-node-test.js, src/components/__tests__/Tabs-test.js, src/components/__tests__/__snapshots__/Tab-test.js.snap, src/components/__tests__/__snapshots__/TabList-test.js.snap, src/components/__tests__/__snapshots__/TabPanel-test.js.snap, src/components/__tests__/__snapshots__/Tabs-test.js.snap, src/helpers/uuid.js, src/index.js
BREAKING CHANGE: React version 18 is required.
Fixes #327
=> Use new `useId` hook from react 18

index.d.ts, package.json, src/components/Tab.js, src/components/Tabs.js
BREAKING CHANGE: Typescript typings are now part of this package. Please uninstall `@types/react-tabs`
=> Add typescript typings to repo

README.md, index.d.ts
=> feat(typescript): Add new type for custom tabs function components

index.d.ts, src/components/Tabs.js, src/components/UncontrolledTabs.js, src/components/__tests__/Tabs-test.js
Currently only up/down buttons can be disabled. This pr adds possibility to disable left/right buttons as well which is helpful for vertical tabs.
=> feat: Allow disable left right buttons

src/components/Tab.js, src/components/TabList.js, src/components/TabPanel.js, src/components/Tabs.js, src/components/UncontrolledTabs.js
fixes https://github.com/reactjs/react-tabs/issues/514
=> refactor: use default parameters
